---
title: "Maps"
author: "Trini et al"
date: "2024-03-05"
output: html_document
---

install.packages("maps")
install.packages("RColorBrewer")

#0 set up 
```{r}
library(tidyverse)
library(sf) 
library(mapview)  
library(tidylog) 
library(dplyr)
library(maps)
library(viridis)
library(cowplot)

library(RColorBrewer)
getwd()
list.files()
list.files('../../BaltimoreStreetTreeProject_Large_Data/')
list.files('../../BaltimoreStreetTreeProject_Large_Data/', recursive = TRUE)
```

# 1 read in variables
```{r}
# Dependent <- read_csv('input_data/Dependent_variable_2025-03-14.csv')
# Dependent <- read_csv('input_data/Dependent_variable_2025-03-27.csv')
# Dependent <- read_csv('input_data/Dependent_variable_2025-04-01.csv')
# Dependent <- read_csv('input_data/Dependent_variable_2025-06-30.csv')
Dependent <- read_csv('input_data/Dependent_variable_2025-07-18.csv')
Independent<- read_csv('input_data/Independent_variable_2025-03-14.csv')


Combined <-
  Dependent |> 
  left_join(Independent, by = "CSA2020") |> 
  select(-geometry)


```


# 2 read in neighborhood boundaries and join to variables
```{r}
bmore_bnia <- 
  st_read('../BaltimoreStreetTreeProject_Large_Data/Community_Statistical_Areas_(2020)/Community_Statistical_Areas__2020_.shp'
          , as_tibble = TRUE) |> #BNIA community delineations
  left_join(Combined, by = 'CSA2020') # combined st_as_sf?

```




#5 Stocking
```{r}
A <- 
  ggplot(data = bmore_bnia) + 
  geom_sf(aes(fill = percent_filled)) + 
  scale_fill_distiller(palette = "YlGn", trans = "reverse") + theme_void(10) +
  guides(fill = guide_legend(title = "Stocking (%)"))
  
```

#6 Target Pit Size 
```{r}
# pct_2.97
B <-
  ggplot(data = bmore_bnia) + 
  geom_sf(aes(fill = pct_2.97)) + 
  scale_fill_distiller(palette = "Reds", trans = "reverse") + theme_void(10)+
  guides(fill = guide_legend(title = "Target pit\nsize (%)"))

```


#7 richness 
```{r}
# fixme rich_tottree
C <- 
  ggplot(data = bmore_bnia) + 
  # geom_sf(aes(fill = rich_tottree)) + 
  geom_sf(aes(fill = rare_rich)) + 
  scale_fill_distiller(palette = "Blues", trans = "reverse") + theme_void(10) +
  # guides(fill = guide_legend(title = "Richness\nNormalized by\nTotal Trees"))
  guides(fill = guide_legend(title = "Rarefied\nrichness"))
```




```{r}
# fixme AvgDBH_smallmed
D <-
  ggplot(data = bmore_bnia) + 
  geom_sf(aes(fill = AvgDBH_smallmed)) + 
  scale_fill_distiller(palette = "RdPu", trans = "reverse", breaks = seq(10, 40, 5)) + theme_void(10)+
  guides(fill = guide_legend(title = "Mean DBH\n(small, cm)"))

```

#8 size 
```{r}
# fixme AvgDBH_large
E <- 
  ggplot(data = bmore_bnia) + 
  geom_sf(aes(fill = AvgDBH_large)) + 
  scale_fill_distiller(palette = "Oranges", trans = "reverse", breaks = seq(10, 40, 5)) + theme_void(10) +
  guides(fill = guide_legend(title = "Mean DBH\n(large, cm)"))
```

#9 perc poor
```{r}
F <- 
  ggplot(data = bmore_bnia) + 
  geom_sf(aes(fill = PercPoor)) + 
  scale_fill_distiller(palette = "Purples", trans = "reverse") + theme_void(10)+
  guides(fill = guide_legend(title = "Poor\ncondition (%)"))
```

#10 
#11 arrange maps
```{r}
Maps <- plot_grid(A, B, C, D, E, F
                  , labels = c('A', 'B', 'C', 'D', 'E', 'F')
                  , ncol = 2, vjust =1)

Maps

ggsave(plot = Maps
       , filename = paste0('figures/Figure_1_maps_street_tree_dbh_', Sys.Date(), '.png')
       # , filename = paste0('figures/Figure_1_maps_street_tree_', Sys.Date(), '.png')
       , width=180
       , height=200
       , unit="mm"
       , dpi=300 )
```

# 12 Table 1 minus road length map series.
```{r}

bmore_bnia |> 
  select(
      'Black population (%)'                         = PercBlk
    , 'White population (%)'                         = PercWhite
    , 'Median household Income (USD)'                = mhhi20
    , 'Bachelor’s Degree Educational Attainment (%)' = bahigher20
    , 'Air Temperature (°C)'                         = avg_temp
    , 'Vacancy (%)'                                  = vacant20
    , 'Impervious surface cover (%)'                 = PercentImp
    # , 'Population density'                           = PopDensity
    # , 'Road length (m)'                               = sum_road_length_m
    )


a <- 
  bmore_bnia |> 
  select(
    'Black\npopulation\n(%)'                         = PercBlk
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Black\npopulation\n(%)`)) + 
  scale_fill_distiller(
      palette = "Blues"
    , trans = "reverse"
    ) + 
  # theme_bw(10) + 
  theme_void(10) +
  NULL

b <- 
  bmore_bnia |> 
  select(
    'White\npopulation\n(%)'                         = PercWhite
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `White\npopulation\n(%)`)) + 
  scale_fill_distiller(
      palette = "Reds"
    , trans = "reverse"
    ) + 
  # theme_bw(10) + 
  theme_void(10) +
  NULL

c <- 
  bmore_bnia |> 
  select(
    'Median\nhousehold\nincome\n(USD)'                = mhhi20
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Median\nhousehold\nincome\n(USD)`)) + 
  scale_fill_viridis() +
  # theme_bw(10) + 
  theme_void(10) +
  NULL


d <- 
  bmore_bnia |> 
  select(
    'Bachelor’s\ndegree\n(%)' = bahigher20
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Bachelor’s\ndegree\n(%)`)) + 
  scale_fill_viridis(option = 'magma') +
  # theme_bw(10) + 
  theme_void(10) +
  NULL

e <- 
  bmore_bnia |> 
  select(
    'Air\ntemperature\n(°C)'                         = avg_temp
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Air\ntemperature\n(°C)`)) + 
  scale_fill_viridis(option = 'F', direction = -1) +
  # theme_bw(10) + 
  theme_void(10) +
  NULL

f <- 
  bmore_bnia |> 
  select(
    'Vacancy\n(%)'                                  = vacant20
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Vacancy\n(%)`)) + 
  scale_fill_distiller(
      palette = "Purples"
    , trans = "reverse"
    ) + 
  # theme_bw(10) + 
  theme_void(10) +
  NULL

g <-
  bmore_bnia |> 
  select(
    'Impervious surface\ncover (%)'                 = PercentImp
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Impervious surface\ncover (%)`)) + 
  scale_fill_distiller(
      palette = "Greys"
    , trans = "reverse"
    ) + 
  # theme_bw(10) + 
  theme_void(10) +
  NULL


h <-
  bmore_bnia |> 
  select(
    'Population\ndensity'                           = PopDensity
    ) |> 
  ggplot() + 
  geom_sf(aes(fill = `Population\ndensity`)) + 
  scale_fill_distiller(
      palette = "RdGy"
    , trans = "reverse"
    ) + 
  # theme_bw(10) + 
  theme_void(10) +
  NULL

socenv_maps <- 
  plot_grid(
      a
    , b
    , c
    , d
    , e
    , f
    , g
    # , h
    , labels = c(
        'A'
      , 'B'
      , 'C'
      , 'D'
      , 'E'
      , 'F'
      , 'G'
      # , 'H'
      )
    , ncol = 2
    , vjust =1)

socenv_maps

# ggsave(filename = paste0('figures/Figure_S1_maps_street_tree_', Sys.Date(), '.png')
#        , width=180
#        , height=220
#        , unit="mm"
#        , dpi=300 )


```

