---
title: "BaltimoreStreetTrees"
author: "Trini et al"
date:  "`r format(Sys.Date())`"
output:
  html_document:
    fig_width: 8
    fig_height: 5
    fig_caption: true
    toc: true
    toc_float: true
    self_contained: true
---

This file gets street trees summarized per neighborhood

read in shapefile by bmore city with neighborhood delineations and combine with street tree data


# 0 set up
```{r}


# load packages

library(tidyverse)
library(sf) #simple features - vector GIS support
library(mapview) #quick web maps 
library(tidylog) #makes dplyr and tidyr verbose
library(dplyr)

# This code is broken, work with Dexter to fix.
# setwd<-("C:\\Users\\trini\\Documents\\Street Trees\\BaltimoreTrees") # there is another way to do this I'll (DHL) show you

getwd()
list.files()
list.files('../../BaltimoreStreetTreeProject_Large_Data/') # means "up one level"
list.files('../../BaltimoreStreetTreeProject_Large_Data/', recursive = TRUE) # means "up one level"
```


# 1 combine street trees and neighborhoods
```{r eval=FALSE, include=FALSE}

street_tree <- 
  st_read('../../BaltimoreStreetTreeProject_Large_Data\\bc_forestry_trees_20190319\\bc_forestry_trees_20190319.shp'
, as_tibble = TRUE) %>% 
  filter(LOC_TYPE == "Street") 

#double check filter for street trees
table(street_tree$LOC_TYPE)

bmore_nb <- 
  st_read('../../BaltimoreStreetTreeProject_Large_Data\\Neighborhood/Neighborhood.shp') |> 
  st_make_valid() |> 
  st_transform(crs = st_crs(street_tree))


# double checks
street_tree |> glimpse()
street_tree |> 
  sample_n(1000) |> # just grab 1000 random points to avoid over-plotting and sensory overload
  mapview(zcol = 'GENUS') # lets color the dots by genus, why not?

bmore_nb |> glimpse()
bmore_nb |> plot() # works
# bmore_nb |> mapview() # fails, gdal errors (Geospatial Data Abstraction Library, https://gdal.org/, open source spatial library)
# bmore_nb |> st_is_valid()
# bmore_nb |> st_make_valid() |> mapview(zcol = 'Population') # seems to work now! updated read in step above


# combining files
combined <- 
  street_tree %>%
  st_join(bmore_nb) %>%
  st_drop_geometry()

# did that joining work?
combined
combined |> glimpse()

# st_write can be used to save out spatial layer of trees with their neighborhood attributes. 
# TODO cut attributes we don't actually need. 
#need to fix this path
combined |> 
  write_csv(paste0('../../BaltimoreStreetTreeProject_Large_Data/street_trees_with_neigh_attributes_', Sys.Date(), '.csv'))

```

## A read in street tree + neighborhood file
```{r}

combined <-
  read_csv('../../BaltimoreStreetTreeProject_Large_Data/street_trees_with_neigh_attributes_2023-06-13.csv')

# exploratory data analysis
combined |> summary()
combined |> glimpse()
combined |> head()
combined |> tail()
```
#clean combined data - get rid of unnecessary columns
```{r}
clean <- combined %>% 
  select(-ID,-OnStr, -OBSERV2, -OBSERV3, -LOC_TYPE, -HARD_SCAPE, -PARCELID, -COLLECTOR, -Inv_Time, -INSPECT_DT, -Inspect_TM, -Notes, -OBJECTID.y) %>% 
  rename(Neighborhood = Name)

```





