---
title: "Baltimore City Streets"
author: "Trini et al"
date:  "`r format(Sys.Date())`"
output:
  html_document:
    fig_width: 8
    fig_height: 5
    fig_caption: true
    toc: true
    toc_float: true
    self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# Load libraries
packs <-c(  'tidyverse' # cuz
          # , 'tidylog'   # prints out what was done in dplyr and tidyr; VERBOSE
          , 'magrittr'  # for all of the the pipes
          , 'sf'        # simple features spatial data suppport and analyses
          , 'janitor'   # pipe-friendly cross tabulations
          ,'tidycensus' # access to Census data in a tidy way
          , 'mapview'   # quick webmaps
          # , 'parzer'    # parses messy coordinates
          , 'tmap'      # thematic mapper
          , 'tictoc'    # timing things.
          , 'DT'        # knitr tables that search/filter
          )

# # check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))
}

# load the libraries
# lapply(packs, library, character.only = TRUE) # raster masks many tidyverse function, be explicit!
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)


# HOLC custom colors
holc_col <- c('#92BC6B', '#92C7C9', '#E7DC6B', '#E47D67')
holc_col2<- c('#92BC6B', '#92C7C9', '#E7DC6B', '#E47D67', '#808080')


# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


d_path <- file.path(getwd(), 'input_data')
```


# are these datasets the same?
```{r}

# get found
list.files('input_data')
list.files('../../evo')
list.files('../../evo/tb_street_trees')

# read in excel
tb_xls <- readxl::read_xlsx('../../evo/tb_street_trees/bc_forestry_trees_20190319.xlsx')

# read in csv
tb_csv <- readr::read_csv('../../evo/tb_street_trees/bc_forestry_trees_20190319.csv')

# read in shapefile
tb_shp <- sf::st_read('../../evo/tb_street_trees/bc_forestry_trees_20190319.shp') |> 
  st_drop_geometry() # this pulls the spatial information OFF the table, leaving what is like the attribute table


# transpose and peek at top few rows for each
tb_xls |> glimpse()
tb_csv |> glimpse()
tb_shp |> glimpse()


tb_xls |> dim()
tb_csv |> dim()
tb_shp |> dim()

# how do the column names compare?
janitor::compare_df_cols(tb_xls, tb_csv, tb_shp)

# what about values
all_equal(tb_xls, tb_csv, tb_shp)

# These files look the same


```


# End
