---
title: "Tree data"
author: "Trini et al"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    fig_width: 8
    fig_height: 5
    fig_caption: true
    toc: true
    toc_float: true
    self_contained: true
---

This file contains all dependent variable data for analysis

# 0 set up 
```{r}
# load packages
library(tidyverse)
library(sf) 
library(mapview)  
library(tidylog) 
library(dplyr)

getwd()
list.files()
list.files('../../BaltimoreStreetTreeProject_Large_Data/')
list.files('../../BaltimoreStreetTreeProject_Large_Data/', recursive = TRUE)
```

# 1 read in street tree data
```{r}
street_tree <- 
  st_read('../../BaltimoreStreetTreeProject_Large_Data\\bc_forestry_trees_20190319\\bc_forestry_trees_20190319.shp'
, as_tibble = TRUE) %>% 
  filter(LOC_TYPE == "Street") 
```

# 2 combine with BNIA neighborhood boundaries
```{r}
bmore_bnia <- st_read('../../BaltimoreStreetTreeProject_Large_Data\\Community Statistical Areas (BNIA neighborhoods)/Community_Statistical_Areas_(CSAs)__Reference_Boundaries.shp') |> #BNIA community delineations
  st_make_valid() |>
  st_transform(crs = st_crs(street_tree))

combined <-  
  street_tree %>%
  st_join(bmore_bnia) %>%
  st_drop_geometry()

combined |> 
  write_csv(paste0('../../BaltimoreStreetTreeProject_Large_Data/street_trees_with_neigh_attributes_', Sys.Date(), '.csv'))
```

 
#total number of trees - 
```{r}

```

#richness
```{r}

```

#evenness
#DBH
#CV of DBH
#% native
#Small trees
#Medium trees
#Large trees

```{r}

```




